---
- name: Setup
  hosts: inetRouter
  become: yes
  


    
    
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
        
    - name: disable ssl for repo epel
      lineinfile: 
        dest: /etc/yum.repos.d/epel.repo
        insertafter: 'enabled=1'
        line: 'sslverify=0'

    - name: Add iptables service
      yum:
        name: iptables-services
        state: present
        
        
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive

    - name: edit sysctl ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
        
    - name: daemon started
      systemd:
        name: iptables
        state: started
        enabled: yes


    - name: copy config
      copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0755'
      with_items:
        - { src: 'inetRouter/ifcfg-eth0', dest: '/etc/sysconfig/network-scripts/' }
        - { src: 'inetRouter/ifcfg-eth1', dest: '/etc/sysconfig/network-scripts/' }
        - { src: 'inetRouter/ifcfg-eth2', dest: '/etc/sysconfig/network-scripts/' } 
        - { src: 'inetRouter/ifcfg-bond0', dest: '/etc/sysconfig/network-scripts/' }
        - { src: 'inetRouter/route-bond0', dest: '/etc/sysconfig/network-scripts/' }
        - { src: 'inetRouter/iptables', dest: '/etc/sysconfig/' }
      notify:
      - restart server
      
  handlers:
  - name: restart server
    reboot:
      reboot_timeout: 120